name: Continuous Integration
on:
  workflow_call:
  push:
  pull_request:
  merge_group:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: { platform: linux, arch: x86_64, os: ubuntu-22.04 }
            target-type: template_debug
            float-precision: single
            dev-build: yes
          - target: { platform: windows, arch: x86_64, os: windows-latest }
            target-type: template_debug
            float-precision: single
            dev-build: yes
          - target: { platform: macos, arch: universal, os: macos-latest }
            target-type: template_debug
            float-precision: single
            dev-build: yes
          - target: { platform: android, arch: arm64, os: ubuntu-22.04 }
            target-type: template_debug
            float-precision: single
            dev-build: yes
          - target: { platform: android, arch: x86_64, os: ubuntu-22.04 }
            target-type: template_debug
            float-precision: single
            dev-build: yes
          - target: { platform: linux, arch: arm64, os: ubuntu-22.04-arm }
            target-type: template_debug
            float-precision: single
            dev-build: yes
          - target: { platform: web, arch: wasm32, os: ubuntu-22.04 }
            target-type: template_debug
            float-precision: single
            dev-build: yes

    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          check-latest: true

      #- name: Setup clang-format
      #  shell: bash
      #  run: |
      #    python -m pip install clang-format
      #- name: Run clang-format
      #  shell: bash
      #  run: |
      #    clang-format src/** --dry-run --Werror

      - name: Install multilib support
        if: ${{ matrix.target.platform == 'linux' && matrix.target.arch == 'x86_32' }}
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib

      - name: Setup godot-cpp
        uses: ./godot-cpp/.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.target.platform }}
          em-version: 3.1.62

      - name: Restore .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}

      - name: Build GDExtension (${{ matrix.target-type }})
        shell: sh
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
        run: |
          scons target=${{ matrix.target-type }} platform=${{ matrix.target.platform }} arch=${{ matrix.target.arch }} precision=${{ matrix.float-precision }} dev_build=${{ matrix.dev-build }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gdextension-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.target-type }}
          path: bin/${{ matrix.target.platform }}/

      - name: Save .scons_cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          scons-cache: ${{ github.workspace }}/.scons-cache/
          cache-name: ${{ matrix.target.platform }}_${{ matrix.target.arch }}_${{ matrix.float-precision }}_${{ matrix.target-type }}