name: Scene Flamegraph

on:
  workflow_dispatch:

jobs:
  Scene_Flamegraph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'   # godot-cpp 通常作为子模块

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.6.1       
          use-dotnet: false
          include-templates: false

      # 编译 GDExtension
      - name: Build GDExtension
        run: |
          pip install scons
          scons platform=linux target=template_debug -j$(nproc)

      - name: Install perf & FlameGraph
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic xvfb
          git clone --depth 1 https://github.com/brendangregg/FlameGraph.git

      - name: Profile scene
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          
          godot --path ./project --import
          godot --path ./project main.tscn & GODOT_PID=$!
          sleep 10
          sudo perf record -F 99 -g -p $GODOT_PID --exclude-kernel -o perf.data -- sleep 25
          sudo chown $(id -u):$(id -g) perf.data
          kill $GODOT_PID

      - name: Generate flamegraph
        run: |
          perf script --dso=libStreamWorld.linux.template_debug.x86_64.so -i perf.data > out.perf
          ./FlameGraph/stackcollapse-perf.pl out.perf > out.folded
          ./FlameGraph/flamegraph.pl out.folded > flamegraph.svg

      - name: Upload flamegraph
        uses: actions/upload-artifact@v4
        with:
          name: scene-flamegraph
          path: flamegraph.svg